config/routes.rb
Rails.application.routes.draw do

  resources :accepteds
  resources :allaccepteds
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :accepteds

  devise_for :users
  #parte publica
  get 'admisiones' => 'public#admisiones'

  get 'desarolladores' => 'public#desarolladores'

  get 'public/index'

  root 'public#index'


  get 'delateAll' =>'requests#delateAll'


  get 'delateAll1' =>'accepteds#delateAll1'

  get 'index' => 'public#index'

  get 'grupos' => 'accepteds#index'

  #gruups
  get 'generate' => 'groups#generate'

  get 'generarGru' => 'groups#saveGroups'

  get 'groups/generate'

  resources :requests do
    collection { post :import}
  end
  resources :specialities





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  validates :name, :numberStudents,  presence: { message: "El campo no puede estar en blanco"}
  validates :morningClasses, presence: {message: "Si no quieres salones en la mañana pon 0"}
  validates :eveningClasses, presence: {message: "Si no quieres salones en la tarde pon 0"}
  validates :eveningClasses, :morningClasses, :numberStudents, numericality: { only_integer: true, message: "Solo numeros"}
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  before_action :set_speciality, only: [:show, :edit, :update, :destroy]

  # GET /specialities
  # GET /specialities.json
  def index
      authorize! :update , Accepted
    @specialities = Speciality.all
  end

  # GET /specialities/1
  # GET /specialities/1.json
  def show
      authorize! :show , Accepted
  end

  # GET /specialities/new
  def new
      authorize! :new , Accepted
    @speciality = Speciality.new
  end

  # GET /specialities/1/edit
  def edit
      authorize! :edit , Accepted
  end

  # POST /specialities
  # POST /specialities.json
  def create
      authorize! :create , Accepted
    @speciality = Speciality.new(speciality_params)

    respond_to do |format|
      if @speciality.save
        format.html { redirect_to @speciality, notice: 'Speciality was successfully created.' }
        format.json { render :show, status: :created, location: @speciality }
      else
        format.html { render :new }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialities/1
  # PATCH/PUT /specialities/1.json
  def update
    respond_to do |format|
      if @speciality.update(speciality_params)
        format.html { redirect_to @speciality, notice: 'Speciality was successfully updated.' }
        format.json { render :show, status: :ok, location: @speciality }
      else
        format.html { render :edit }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1
  # DELETE /specialities/1.json
  def destroy
      authorize! :destroy , Accepted
    @speciality.destroy
    respond_to do |format|
      format.html { redirect_to specialities_url, notice: 'Speciality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speciality
      @speciality = Speciality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speciality_params
      params.require(:speciality).permit(:name, :morningTurn, :eveningTurn, :morningClasses, :eveningClasses, :numberStudents)
    end
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/_form.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

<%= render 'helpersLayout/header' %>

<section class="PrincipalNewSpecialities mainBox">

<%= form_for(speciality) do |f| %>



  <div class="container_new_specialities sombra_speciality">
    <p class="welcome_new_specialities">Nueva Especialidad</p>
    <p class="text_new_specialities">Aquí podrás añadir una nueva especialidad</p>
    <%= image_tag("lap.png", class: "lap_new_specialities")%>
  </div>



  <div class="container_new_specialities2 sombra_speciality">
    <div>
      <%= f.label :name, "NOMBRE", class: "speciality_texto" %>
      <%= f.text_field :name, class:"form-input_speciality "%>
    </div>

    <div>
      <%= f.label :Turn, "TURNO", class: "speciality_texto acomodar_etiqueta_speciality" %>
      <%= f.label :morningTurn, "TM", class: "speciality_texto acomodar_tm_speciality" %>
      <%= f.check_box :morningTurn, placeholder: "TM", class:"caja_speciality" %>
      <%= f.label :morningTurn, "Turno Matutino", class: "remember_speciality" %>
      <%= f.label :eveningTurn, "TV", class: "speciality_texto acomodar_tv_speciality" %>
      <%= f.check_box :eveningTurn, placeholder: "TV", class:"caja_speciality" %>
      <%= f.label :morningTurn, "Turno Vespertino", class: "remember_speciality" %>
    </div>

    <div>
      <%= f.label :morningClasses , "CLASES MATUTINAS", class: "speciality_texto acomodar_speciality"  %>
      <%= f.text_field :morningClasses, class:"form-input_speciality clases_matutinas_speciality" %>
    </div>

    <div>
      <%= f.label :eveningClasses, "CLASES VESPERTINAS", class: "speciality_texto acomodar_speciality2" %>
      <%= f.text_field :eveningClasses, class:"form-input_speciality clases_vespertinas_speciality" %>
    </div>

    <div>
      <%= f.label :numberStudents , "NÚMERO DE ESTUDIANTES", class: "speciality_texto acomodar_speciality2" %>
      <%= f.number_field :numberStudents, class:"form-input_speciality numero_estudiantes_speciality" %>
    </div>

    <div>
      <%= f.submit "CREAR ESPECIALIDAD", class:"btn-speciality"%>
      <%= link_to 'CANCELAR', specialities_path, class: "btn-speciality acomodar_btn_speciality" %>
    </div>

    <% if speciality.errors.any? %>
      <div id="errorrs">
        <h2><%= pluralize(speciality.errors.count, "errores") %>   ,Corrije los errores para continuar</h2>

        <ul>
        <% speciality.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
   <% end %>
  </div>
</section>

app/views/specialities/edit.html.erb
<%= render 'form', speciality: @speciality %>

<%= link_to 'Show', @speciality %> |
<%= link_to 'Back', specialities_path %>

app/views/specialities/index.html.erb
<%= render 'helpersLayout/header' %>


<section class="espe">

  <div class="h1_sol_pri etiqueta_solicitud">
      <h1>ESPECIALIDADES EXITENTES</h1>
  </div>

  <table>
      <thead class="hola_sol">
        <tr class="hola_sol">
          <th class="etiqueta_solicitud cam_in_sol">NOMBRE</th>
          <th class="etiqueta_solicitud cam_in_sol">T/MATUTINO</th>
          <th class="etiqueta_solicitud cam_in_sol">T/VESPERTINO</th>
          <th class="etiqueta_solicitud cam_in_sol">CLASES MAT.</th>
          <th class="etiqueta_solicitud cam_in_sol">CLASES VES.</th>
          <th class="etiqueta_solicitud cam_in_sol">N. ESTUDIANTES</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <tbody>
      <% @specialities.each do |speciality| %>
        <tr>

          <td class="etiqueta_solicitud especialidades_soli"><%= speciality.name %></td>
          <td class="etiqueta_solicitud especialidades_soli2">
            <% if speciality.morningTurn %>
              <strong>Habilitado</strong>
            <%elsif speciality.morningTurn == false %>
              <strong>Deshabilitado</strong>
            <% end %>
          </td>
          <td class="etiqueta_solicitud especialidades_soli2">
            <% if speciality.eveningTurn %>
              <strong>Habilitado</strong>
            <%elsif speciality.eveningTurn == false %>
              <strong>Deshabilitado</strong>
            <% end %>
          </td>
          <td class="etiqueta_solicitud especialidades_soli2"><%= speciality.morningClasses %></td>
          <td class="etiqueta_solicitud especialidades_soli2"><%= speciality.eveningClasses %></td>
          <td class="etiqueta_solicitud especialidades_soli2"><%= speciality.numberStudents %></td>

          <td class="etiqueta_solicitud especialidades_soli3"><%= link_to '', speciality, class:"icon-user" %></td>
          <td class="etiqueta_solicitud especialidades_soli3"><%= link_to '', edit_speciality_path(speciality), class:"icon-pencil" %></td>
          <td class="etiqueta_solicitud especialidades_soli3"><%= link_to '', speciality, method: :delete, class:"icon-bin2", data: { confirm: '¿Desea eliminar el elemento?' } %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
</section>


<%= link_to 'AGREGAR', new_speciality_path, class: "btn-speciality acomodar_sol_index" %>

app/views/specialities/new.html.erb
<%= render 'form', speciality: @speciality %>

app/views/specialities/show.html.erb
<%= render 'helpersLayout/header' %>
<div class="mainBox">

  <div class="div_nueva_especialidad">

    <div class="imagen_nuevaespecialidad">
      <%= image_tag("lap.png", class: "lap_specialities")%>
    </div>

    <div class="div_nueva_agregada">
      <p class="etiqueta_solicitud cam_in_sol speciality_new_index name_new_index">
        <strong>NOMBRE: </strong>
        <%= @speciality.name %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>TURNO MATUTINO: </strong>
        <%if @speciality.morningTurn %>
          <strong>Habilitado</strong>
        <% elsif @speciality.morningTurn == false%>
          <strong>Deshabilitado</strong>
        <% end %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>TURNO VESPERTINO: </strong>
        <%if @speciality.eveningTurn %>
          <strong>Habilitado</strong>
        <% elsif @speciality.eveningTurn == false%>
          <strong>Deshabilitado</strong>
        <% end %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>CLASES MATUTINAS: </strong>
        <%= @speciality.morningClasses %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>CLASES VESPERTINAS:</strong>
        <%= @speciality.eveningClasses %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>N. DE ESTUDIANTES:</strong>
        <%= @speciality.numberStudents %>
      </p>

      <div class="botones_index_sp">
        <%= link_to 'EDITAR', edit_speciality_path(@speciality), class: "btn-speciality acomodar_sol_index edit_sp_index"%>
        <%= link_to 'REGRESAR', specialities_path, class: "btn-speciality acomodar_sol_index back_sp_index" %>
      </div>
    </div>
  </div>
</div>