config/routes.rb
Rails.application.routes.draw do

  resources :accepteds
  resources :allaccepteds
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :accepteds

  devise_for :users
  #parte publica
  get 'admisiones' => 'public#admisiones'

  get 'desarolladores' => 'public#desarolladores'

  get 'public/index'

  root 'public#index'


  get 'delateAll' =>'requests#delateAll'


  get 'delateAll1' =>'accepteds#delateAll1'

  get 'index' => 'public#index'

  get 'grupos' => 'accepteds#index'

  #gruups
  get 'generate' => 'groups#generate'

  get 'generarGru' => 'groups#saveGroups'

  get 'groups/generate'

  resources :requests do
    collection { post :import}
  end
  resources :specialities





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  def self.import(file)
      CSV.foreach(file.path, headers: true, :encoding => 'utf-8') do |row|
        Request.create! row.to_hash


    end

  end

  def self.to_csv
  CSV.generate do |csv|
    csv << column_names
    all.each do |product|
      csv << product.attributes.values_at(*column_names)
    end
  end
end

  def self.search(query)
  where("name like ?", "%#{query}%")
  end #sel.search

  validates :name, :apellidoPaterno, :apellidoMaterno, presence: { message: "El campo no puede estar en blanco"}
  validates :examMark, :schoolAverage, :numericality => { :greater_than_or_equal_to => 6, :less_than_or_equal_to => 10, message: "Ingresa un numero que sea mayor 6 o un numero menor o igual a 10" }
  validate :validate_specialities


  private
    def validate_specialities
      if speciality == secondSpeciality
        errors.add(:speciality, "No se puede elegir la misma especialidad")
        errors.add(:secondSpeciality, "No se puede elegir la misma especialidad")
      end
    end



end#class

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :set_specialities, only: [:new, :edit, :create]

  # GET /requests
  # GET /requests.json
  def index

    authorize! :update , Request


    @requests = Request.all

    if params[:search]
    @requests = Request.search(params[:search]).order("created_at DESC")
    else
    @requests = Request.all.order('created_at DESC')
    end

=begin
    @confirm = Request.all
    @requests.each_with_index do |x,p|
      @confirm.each_with_index do |j,b|
        if p < b
          if x.name == j.name and x.apellidoPaterno == j.apellidoPaterno and x.apellidoMaterno == j.apellidoMaterno
            x.delete
          end
        end
      end

    end
=end

  end#index

  # GET /requests/1
  # GET /requests/1.json
  def show

    authorize! :show , Request
  end

  def delateAll
      authorize! :destroy , Request
      Request.destroy_all

  end

  # GET /requests/new
  def new
    authorize! :create , Request
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
    authorize! :edit , Request
  end

  # POST /requests
  # POST /requests.json
  def create
    authorize! :create , Request

    @request = Request.new(request_params)



    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update

    authorize! :update , Request

    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy

    authorize! :destroy , Request

    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import

    authorize! :update , Request
    Request.import(params[:file])
    redirect_to requests_url, notice: "la base de datos fue importada correctamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    def set_specialities
      @specialities = Array.new

      Speciality.all.each do |x|
        @specialities.push(x.name.upcase)
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :apellidoPaterno, :apellidoMaterno, :examMark, :schoolAverage, :isForeign, :speciality, :secondSpeciality)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<%= render 'helpersLayout/header' %>

<div class="container_solicitud mainBox">

</div>

<section class="PrincipalNewSpecialities mainBox">



    <div class="container_solicitud2">

      <%= form_for(request) do |f| %>

      <div class="solicitud_y_textos">
        <p class="etiqueta_solicitud">Nueva Solicitud</p>
        <p class="solicitud_texto text_new_specialities">Aquí podrás añadir una nueva solicitud</p>
        <div class="datos_solicitud">
          <%= image_tag("user.png", class: "user_solicitud")%>
          <p class="text_new_specialities soli_datos">Datos</p>
        </div>
      <div id="super">
          <% if request.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(request.errors.count, "errores") %>   ,Corrije los errores para continuar</h2>

              <ul>
              <% request.errors.full_messages.each do |message| %>
                <li>-<%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>


        </div>


      </div>

      <div class="formulario_solicitud">

        <div>
          <%= f.label :name, "NOMBRE", class: "etiqueta_solicitud mover_solicitud_ele" %>
          <%= f.text_field :name, class:"form-input_solicitud mover_solicitud_ele mover_ele" %>
        </div>

        <div class="contiene_apellidos">
          <div class="mover_apellido_paterno margen_apeliido">
            <%= f.label :apellidoPaterno, "APELLIDO PATERNO", class: "etiqueta_solicitud" %>
            <%= f.text_field :apellidoPaterno, class:"form-input_solicitud" %>
          </div>

          <div class="mover_apellido_paterno margen_apeliido2">
            <%= f.label :apellidoMaterno, "APELLIDO MATERNO", class: "etiqueta_solicitud" %>
            <%= f.text_field :apellidoMaterno, class:"form-input_solicitud" %>
          </div>
        </div>

        <div>
          <%= f.label :examMark, "PUNTAJE DE EXAMEN", class: "etiqueta_solicitud mover_solicitud_ele"  %>
          <%= f.text_field :examMark, class:"form-input_solicitud mover_solicitud_ele mover_ele " %>
        </div>

        <div>
          <%= f.label :schoolAverage, "PROMEDIO DE SECUNDARIA", class: "etiqueta_solicitud mover_solicitud_ele" %>
          <%= f.text_field :schoolAverage, class:"form-input_solicitud mover_solicitud_ele mover_ele" %>
        </div>

        <div class="contiene_apellidos">
          <div class="mover_apellido_paterno margen_apeliido mover_esp">
            <%= f.label :speciality, "ESPECIALIDAD", class: "etiqueta_solicitud mover_solicitud_ele" %>
            <%= f.select(:speciality, options_for_select(@specialities), {}, {class:"form-input_solicitud mover_solicitud_ele mover_ele"})%>
          </div>

          <div class="mover_apellido_paterno margen_apeliido2 mover_esp2">
            <%= f.label :secondSpeciality, "SEGUNDA ESPECIALIDAD", class: "etiqueta_solicitud mover_solicitud_ele mover_solicitud_ele mover_ele" %>
            <%= f.select(:secondSpeciality, options_for_select(@specialities), {}, {:class => "form-input_solicitud mover_solicitud_ele mover_ele"})%>

          </div>
      </div>

      <div class="finalBo">
        <a class="returBottom" href="/requests">Cancelar</a>
        <%= f.submit "CREAR", class:"crearBottom" %>
      </div>

  <% end %>
</section>

app/views/requests/delateAll.html.erb
<div class="actionsBox sombra">
  <div class="boxImage">
    <%= image_tag('trashlogo.svg',:width => 200, :height => 150, :id => ''  )  %>
  </div>
  <div class="boxText">
    <p class="boxTitulo">Las solicitudes han sido eliminadas</p>
    <div class="description">
      <p></p>
    </div>
    <div class="returnBotton">
      <a href="requests"><%= image_tag('returnlogo.svg',:width => 50, :height => 100, :id => ''  )  %></a>
    </div>

  </div>
</div>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>


<%= link_to 'VER', @request %> |
<%= link_to 'BACK', requests_path %>

app/views/requests/index.html.erb
<div id="load">
  <div class="sk-folding-cube">
    <div class="sk-cube1 sk-cube"></div>
    <div class="sk-cube2 sk-cube"></div>
    <div class="sk-cube4 sk-cube"></div>
    <div class="sk-cube3 sk-cube"></div>
  </div>
  <hi>Loading, please wait...</hi>
</div>

<%= render 'helpersLayout/header' %>

<section class="mainBox" id="request_section">

  <div id="actionR">
    <div id="move_titu">
      <h1 id="titu">SOLICITUDES</h1>
    </div>
    <div id="actions_request">
      <ul>

        <li class="displayFlexAction"><span class="icon-plus move_icon"></span><p class="move_nuevaSo"><%= link_to 'Nueva Solicitud', new_request_path %></p></li>
        <li id="loading"><span  class="icon-bin move_icon" ></span><span id="destroy_requests" class="eliminarSolicitudes">Eliminar</span></li>
        <li>
          <div class="moveActions_Request">
            <%= form_tag import_requests_path, multipart: true do  %>
                <%= file_field_tag :file%>

                <%= submit_tag "Importar", :id =>"loading"%>

            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div id="solicitudes">
    <div class="h1_sol_pri etiqueta_solicitud total_sol">
      <p>Total de solicitudes: <%=Request.all.length%></p>
    </div>

    <table>
      <thead class="hola_sol">
        <tr class="hola_sol">
          <th class="etiqueta_solicitud cam_in_sol">Nombre</th>
          <th class="etiqueta_solicitud cam_in_sol">Apellido paterno</th>
          <th class="etiqueta_solicitud cam_in_sol">Apellido materno</th>
          <th class="etiqueta_solicitud cam_in_sol">Examen</th>
          <th class="etiqueta_solicitud cam_in_sol">Secundaria</th>
          <th class="etiqueta_solicitud cam_in_sol">Primera Especialidad</th>
          <th class="etiqueta_solicitud cam_in_sol">Segunda Especialidad</th>
          <th class="etiqueta_solicitud cam_in_sol">Foraneo</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @requests.each do |request| %>
          <tr>

            <td class="etiqueta_solicitud especialidades_soli"><%= request.name %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.apellidoPaterno %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.apellidoMaterno %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.examMark %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.schoolAverage %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.speciality %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.secondSpeciality %></td>
            <td class="etiqueta_solicitud especialidades_soli2"><%= request.isForeign %></td>
            <td class="etiqueta_solicitud especialidades_soli3"><%= link_to '', edit_request_path(request), class:"icon-pencil" %></td>
            <td class="etiqueta_solicitud especialidades_soli3"><%= link_to '', request, method: :delete, class:"icon-bin2", data: { confirm: '¿Desea eliminar el elemento?' } %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>
<br>

app/views/requests/new.html.erb
<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<%= render 'helpersLayout/header' %>
<div class="mainBox">

  <div class="div_nueva_especialidad div_nueva_solicitud">

      <div class="imagen_nuevaespecialidad">
        <%= image_tag("lap.png", class: "lap_specialities lap_srq")%>
      </div>

      <div class="div_nueva_agregada nueva_agregada_sol">
        <p class="etiqueta_solicitud cam_in_sol speciality_new_index name_req_index">
          <strong>Nombre: </strong>
          <%= @request.name %>
        </p>

        <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
          <strong>Apellido Paterno: </strong>
          <%= @request.apellidoPaterno %>
        </p>

        <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
          <strong>Apellido Materno: </strong>
          <%= @request.apellidoMaterno %>
        </p>

        <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
          <strong>Calificación Examen:</strong>
          <%= @request.examMark %>
        </p>

        <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
          <strong>Promedio Secundaria:</strong>
          <%= @request.schoolAverage %>
        </p>

        <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
          <strong>Especialidad:</strong>
          <%= @request.speciality %>
        </p>

        <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
          <strong>Segunda Espacialidad:</strong>
          <%= @request.secondSpeciality %>
        </p>

        <%= link_to 'EDITAR', edit_request_path(@request), class: "btn-speciality acomodar_sol_index edit_sp_index " %>
        <%= link_to 'REGRESAR', requests_path, class: "btn-speciality acomodar_sol_index back_sp_index back_rq_index" %>
      </div>
    </div>
  </div>
</div>