config/routes.rb
Rails.application.routes.draw do

  resources :accepteds
  resources :allaccepteds
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :accepteds

  devise_for :users
  #parte publica
  get 'admisiones' => 'public#admisiones'

  get 'desarolladores' => 'public#desarolladores'

  get 'public/index'

  root 'public#index'


  get 'delateAll' =>'requests#delateAll'


  get 'delateAll1' =>'accepteds#delateAll1'

  get 'index' => 'public#index'

  get 'grupos' => 'accepteds#index'

  #gruups
  get 'generate' => 'groups#generate'

  get 'generarGru' => 'groups#saveGroups'

  get 'groups/generate'

  resources :requests do
    collection { post :import}
  end
  resources :specialities





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accepted.rb
class Accepted < ApplicationRecord
  validates :name, :apellidoPaterno, :apellidoMaterno, presence: { message: "El campo no puede estar en blanco"}
end

app/controllers/accepteds_controller.rb
class AcceptedsController < ApplicationController
  before_action :set_accepted, only: [:show, :edit, :update, :destroy]
  before_action :set_specialities, only: [:new, :edit, :create]

  # GET /accepteds
  # GET /accepteds.json



  def index
      authorize! :update , Accepted
    @accepteds = Accepted.all
    @noAccepted = Array.new
    @solicitudes = Request.all
    @rechazados = Array.new
    @losAceptados = Allaccepted.all

    @solicitudes.each do |o|
      @losAceptados.each do |j|
        if o.name == j.name and o.apellidoPaterno == j.apellidoPaterno and o.apellidoMaterno == j.apellidoMaterno
          o.name = "modificado"
        end#if
      end#accepted2
    end#accepted
    @solicitudes.each do |x|
      if x.name != "modificado"
        @rechazados.push(x)
      end
    end






    #buscador en la zona de grupos






  if params[:search]
    @sgroups = Accepted.search(params[:search]).order("created_at DESC")
  else
    @sgroups = Accepted.all.order('created_at DESC')
  end





#para  exportar en .csv
@export = Accepted.order(:finalSpeciality)
   respond_to do |format|
     format.html
     format.csv { send_data @export.to_csv }
   end

        #Este array contiene todos los posibles grupos
        @groups = Array.new
        #Este array identifica al grupo con una letra en vez de un número
        @groupIdentifier = ['nill', 'A', 'B', 'C', 'D', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

        #Calculamos todos los grupos posibles
        Speciality.all.each do |s|
          #Grupos de la mañana
          if s.morningTurn
            for i in (1..s.morningClasses)
              @groups.push(Hash.new({:speciality => s.name, :turn => 'M' , :group => @groupIdentifier[i]  }))
            end #for Classes
          end #if else
          #Grupos de la tarde
          if s.eveningTurn
            for i in (1..s.eveningClasses)
              @groups.push(Hash.new({:speciality => s.name, :turn => 'V' , :group => @groupIdentifier[i]  }))
            end #for Classes
          end #if else

        end #Speciality.each
  end

  # GET /accepteds/1
  # GET /accepteds/1.json
  def show
      authorize! :show , Accepted
  end

  # GET /accepteds/new
  def new
      authorize! :create , Accepted
    @accepted = Accepted.new
  end

  # GET /accepteds/1/edit
  def edit
      authorize! :edit , Accepted
  end

  def delateAll1
      authorize! :destroy , Accepted
      #Request.destroy_all
      Allaccepted.destroy_all
      Accepted.destroy_all
      #Speciality.destroy_all
      redirect_to "/grupos"
  end
  # POST /accepteds
  # POST /accepteds.json
  def create
        authorize! :create , Accepted
    @accepted = Accepted.new(accepted_params)

    respond_to do |format|
      if @accepted.save
        format.html { redirect_to @accepted, notice: '' }
        format.json { render :show, status: :created, location: @accepted }
      else
        format.html { render :new }
        format.json { render json: @accepted.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accepteds/1
  # PATCH/PUT /accepteds/1.json
  def update
      authorize! :destroy , Accepted
    respond_to do |format|
      if @accepted.update(accepted_params)
        format.html { redirect_to @accepted, notice: '' }
        format.json { render :show, status: :ok, location: @accepted }
      else
        format.html { render :edit }
        format.json { render json: @accepted.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accepteds/1
  # DELETE /accepteds/1.json
  def destroy
      authorize! :destroy , Accepted
      authorize! :manage , Request
    @accepted.destroy
    respond_to do |format|
      format.html { redirect_to accepteds_url, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accepted
      @accepted = Accepted.find(params[:id])
    end


    def set_specialities
      @specialities = Array.new

      Speciality.all.each do |x|
        @specialities.push(x.name.upcase)
      end

    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def accepted_params
      params.require(:accepted).permit(:name, :apellidoPaterno, :apellidoMaterno, :examMark, :schoolAverage, :speciality, :secondSpeciality, :finalSpeciality, :turn, :group, :isForeign)
    end
end

app/helpers/accepteds_helper.rb
module AcceptedsHelper
end

app/views/accepteds/_form.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

<%= render 'helpersLayout/header' %>
<section class="PrincipalNewSpecialities mainBox">



  <%= form_for(accepted) do |f| %>
    <% if accepted.errors.any? %>
      <div id="superError">
        <h2><%= pluralize(accepted.errors.count, "campos sin rellenar") %>,    Llena los campos para continuar</h2>


      </div>
    <% end %>
    <%@turnos = ['M','V']%>

    <div class="container_new_specialities sombra_speciality cambio_div_alum_rec">
      <%= image_tag("lap.png", class: "lap_alum_recom")%>
      <p class="welcome_alum_recom welcome_new_specialities">ALUMNO</p>
    </div>

    <div class="container_new_specialities2 sombra_speciality">
      <div>
        <%= f.label :name, "NOMBRE", class: "speciality_texto comodar_alum_re2" %>
        <%= f.text_field :name, class:"form-input_speciality comodar_alum_re" %>
      </div>

      <div>
        <%= f.label :apellidoPaterno, "APELLIDO PATERNO", class: "speciality_texto acomodar_alum_re"  %>
        <%= f.text_field :apellidoPaterno, class:"acomodar_alum_re2 form-input_speciality "%>
      </div>

      <div>
        <%= f.label :apellidoMaterno, "APELLIDO MATERNO", class: "speciality_texto acomodar_alum_re"  %>
        <%= f.text_field :apellidoMaterno, class:"form-input_speciality acomodar_alum_re2 acomodar_alum_re3" %>
      </div>

      <div>
        <%= f.label :finalSpeciality, "ESPECIALIDAD", class: "speciality_texto acomodar_alum_re"  %>
        <%= f.select(:finalSpeciality, options_for_select(@specialities), {}, {class:"acomodar_alum_re2 form-input_speciality acomodar_alum_re4"})%>
      </div>

      <div>
        <%= f.label :turn, "TURNO", class: "speciality_texto acomodar_alum_re"  %>
        <%= f.select(:turn, options_for_select(@turnos), {}, {class:"acomodar_alum_re2 form-input_speciality acomodar_alum_re5"}) %>
      </div>
      <%@letrasGrupos = ['null', 'A', 'B', 'C', 'D', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']%>
      <div>
        <%= f.label :group, "GRUPO", class: "speciality_texto acomodar_alum_re"  %>
        <%= f.select(:group, options_for_select(@letrasGrupos), {}, { class:"acomodar_alum_re2 form-input_speciality acomodar_alum_re6"}) %>
      </div>

      <div>
        <%= f.submit "CREAR", class:"btn-alum_recom"%>
        <%= link_to 'CANCELAR', accepteds_path, class: "btn-speciality acomodar_btn_alum_recom" %>
      </div>
    <% end %>
  </div>

</section>

app/views/accepteds/_noAccepteds.html.erb
<script type="text/javascript">




</script>

<section id="rechazadosBox">
    <div class="h1_sol_pri etiqueta_solicitud total_sol">
      <p>Total de rechazados: <%=@rechazados.length%></p>
    </div>

    <table class="tablaRecha">
      <thead class="hola_sol">
        <tr class="hola_sol">
          <th class="etiqueta_solicitud cam_in_sol">Nombre</th>
          <th class="etiqueta_solicitud cam_in_sol">Apellido paterno</th>
          <th class="etiqueta_solicitud cam_in_sol">Apellido materno</th>
          <th class="etiqueta_solicitud cam_in_sol">Examen</th>
          <th class="etiqueta_solicitud cam_in_sol">Secundaria</th>
          <th class="etiqueta_solicitud cam_in_sol">Primera Especialidad</th>
          <th class="etiqueta_solicitud cam_in_sol">Segunda Especialidad</th>

          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="filasRecha">
        <% @rechazados.each do |request| %>
          <tr>
            <td class="filasRecha"><%= request.name %></td>
            <td class="filasRecha"><%= request.apellidoPaterno %></td>
            <td class="filasRecha"><%= request.apellidoMaterno %></td>
            <td class="filasRecha"><%= request.examMark %></td>
            <td class="filasRecha"><%= request.schoolAverage %></td>
            <td class="filasRecha"><%= request.speciality %></td>
            <td class="filasRecha"><%= request.secondSpeciality %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

</section>

app/views/accepteds/edit.html.erb
<h1>Editing Accepted</h1>

<%= render 'form', accepted: @accepted %>

<%= link_to 'Show', @accepted %> |
<%= link_to 'Back', accepteds_path %>

app/views/accepteds/index.html.erb
<%= render 'helpersLayout/header' %>

<section class="acceptedSection">
  <p id="notice"><%= notice %></p>
  <div class="groupAc">
    <div class="move_grupo">
      <h1 class="grupoT">GRUPOS</h1>
    </div>
    <div class="actionsG">
      <ul>
        <%if Accepted.all.length == 0%>
          <li class="displayFlexAction" ><span class="icon-cog"></span><a class="move_generar" id="gen" href="/generate">GENERAR GRUPOS</a></li>
        <%end%>
      <%if Accepted.all.length > 0%>
        <li class="displayFlexAction"><span class="icon-plus"></span><p><%= link_to 'Agregar', new_accepted_path %></p></li>
        <li class="displayFlexAction" id="loading"> <span class="icon-bin"></span><a href="/delateAll1" class="move_vaciar">Vaciar bases de datos</a></li>
        <li><span class="icon-address-book"></span><a href="#" class="move_revisarGrupos"> Revisar grupos </a>
          <ul>
            <li class="modi">
              <p id="ver_matutino" class="turnos">Turno Matutino</p>
            </li>
            <li>
              <p id="ver_vespertino" class="turnos">Turno Verpertino</p>
            </li>
            <li>
              <p id="ver_none" class="turnos">Sin especialidad</p>
            </li>

          </ul>
        </li>
        <li >
          <span class="icon-blocked"></span><p id="aparecer">Rechazados</p>
        </li>
      </ul>
      <%end%>
    </div>
  </div>
  <div class="renders">
    <% if Accepted.all.length > 0%>
      <%= render 'helpersLayout/groupsFinderA' %>
      <%= render 'helpersLayout/groupsLayoutA' %>
      <%= render 'noAccepteds'%>
    <% end %>
  </div>
</section>

app/views/accepteds/new.html.erb
<%= render 'form', accepted: @accepted %>

app/views/accepteds/show.html.erb
<%= render 'helpersLayout/header' %>
<div class="mainBox">
  <div class="div_nueva_especialidad div_nueva_solicitud2">

    <div class="imagen_nuevaespecialidad">
      <%= image_tag("lap.png", class: "lap_specialities lap_srq")%>
    </div>

    <div class="div_nueva_agregada nueva_agregada_sol">

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index name_req_index">
        <strong>Nombre:</strong>
        <%= @accepted.name %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>Apellido Paterno:</strong>
        <%= @accepted.apellidoPaterno %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>Apellido Materno:</strong>
        <%= @accepted.apellidoMaterno %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>Especialidad:</strong>
        <%= @accepted.finalSpeciality %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>Turno:</strong>
        <%= @accepted.turn %>
      </p>

      <p class="etiqueta_solicitud cam_in_sol speciality_new_index">
        <strong>Grupo:</strong>
        <%= @accepted.group %>
      </p>

      <%= link_to 'EDITAR', edit_accepted_path(@accepted), class: "btn-speciality acomodar_sol_index edit_sp_index "%>
      <%= link_to 'REGRESAR', accepteds_path, class: "btn-speciality acomodar_sol_index back_sp_index back_rq_index" %>
      </div>
    </div>
  </div>
</div>